  - name: (Asthetics) Tap Hack Nerd Font
    homebrew_tap:
      name: homebrew/cask-fonts
      state: present
  - name: (Asthetics) install hack-nerd-font
    homebrew_cask:
      pkg: font-hack-nerd-font
      state: present
  - name: (Asthetics) Install base16 colorscheme
    git:
      repo: https://github.com/chriskempson/base16-shell.git
      dest: ~/.config/base16-shell
      update: yes
